// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import PersonalQAConcept from "./PersonalQA/PersonalQAConcept.ts";
import InsightMiningConcept from "./InsightMining/InsightMiningConcept.ts";
import QuickCheckInsConcept from "./QuickCheckIns/QuickCheckInsConcept.ts";
import MealLogConcept from "./MealLog/MealLogConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SessioningConcept from "./Sessioning/SessioningConcept.ts";
import SwapSuggestionsConcept from "./SwapSuggestions/SwapSuggestionsConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";

export type { default as PersonalQAConcept } from "./PersonalQA/PersonalQAConcept.ts";
export type { default as InsightMiningConcept } from "./InsightMining/InsightMiningConcept.ts";
export type { default as QuickCheckInsConcept } from "./QuickCheckIns/QuickCheckInsConcept.ts";
export type { default as MealLogConcept } from "./MealLog/MealLogConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SessioningConcept } from "./Sessioning/SessioningConcept.ts";
export type { default as SwapSuggestionsConcept } from "./SwapSuggestions/SwapSuggestionsConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const PersonalQA = Engine.instrumentConcept(new PersonalQAConcept(db));
export const InsightMining = Engine.instrumentConcept(new InsightMiningConcept(db));
export const QuickCheckIns = Engine.instrumentConcept(new QuickCheckInsConcept(db));
export const MealLog = Engine.instrumentConcept(new MealLogConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Sessioning = Engine.instrumentConcept(new SessioningConcept(db));
export const SwapSuggestions = Engine.instrumentConcept(new SwapSuggestionsConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
